import 'package:mongo_dart/mongo_dart.dart';

List<String> localities = ['Aundh',
  'Baner',
  'Bhosari',
  'Camp',
  'Dhayari',
  'Fatima Nagar',
  'Hadapsar',
  'Hinjewadi',
  'Kalyani Nagar',
  'Katraj',
  'Kondhwa',
  'Koregaon Park',
  'Lavasa',
  'Pashan',
  'Pimpri-Chinchwad',
  'Pimple Saudagar',
  'Viman Nagar',
  'Wakad',
  'Yerwada',
  'Shivaji Nagar',
  'Nashik Phata',
  'Wagholi',
  'Talegaon',
  'Sus',
  'Bavdhan',
  'Balewadi',
  'Bhugaon',
  'Navi Peth',
  'Dhole Patil Road',
  'Erandwane',
  'Kothrud',
  'Pimple Gurav'];
